
- name: launch database
  docker_container:
    name: database_devops
    image: "abrosse/tp-devops-database:1.0"
    env:
      POSTGRES_PASSWORD: pwd
    networks:
    - name: "devops-network"


    
