- name: launch proxy
  docker_container:
    name: httpd
    image: "abrosse/tp-devops-httpd:latest"
    pull: yes
    ports:
     - "{{ port_http }}"
    networks:
     - name: "devops-network"
    env:
     DATABASE_HOST: database
     DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
