- name: launch proxy
  docker_container:
    name: httpd
    image: "tp-devops-httpd:latest"
    pull: yes
    ports:
     - 80:80
    networks:
     - name: "devops-network"
    env:
     DATABASE_HOST: database
     DATABASE_PASSWORD: pwd
