- name: launch backend container
  docker_container:
    name: simple-api
    image: "abrosse/tp-devops-simple-api:latest"
    pull: yes
    ports:
     - "{{ port_backend }}}"
    networks:
     - name: "devops-network"
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: "{{ DATABASE_PASSWORD }}"
      DATABASE_PORT: "{{ db_port }}"
      DATABASE_NAME: db
