- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - env.yml

  tasks:
   - name: Test connection
     ping:

  roles: 
    - install_docker
    - create_network
    - launch_database
    - proxy